#!/bin/bash
### BEGIN INIT INFO
## Provides:          http2https
## Required-Start:    $local_fs $network
## Required-Stop:     $local_fs
## Default-Start:     2 3 4 5
## Default-Stop:      0 1 6
## Short-Description: http2https
## Description:       http2https for fun
#### END INIT INFO

# Source function library.
#. /etc/init.d/functions

#Replace your user and workdir
user=admin
workdir=/home/admin/http2https

start() {
    # code to start app comes here
    sudo -u $user bash $workdir/run.sh
}

stop() {
    # code to stop app comes here
    sudo -u $user bash $workdir/kill.sh
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    #status)
       # code to check status of app comes here
       # example: status program_name
       # ;;
    *)
       echo "Usage: $0 {start|stop|restart}"
esac

exit 0